samples: 
  - example
  
word_length: 10
min_word_length: 8

tf_metadata_file: "TF_metadata"

tf_database_file: "JASPAR2022_CORE_vertebrates_non-redundant_pfms_meme"

enrichment_cutoffs:
  percent_kmer_5p: 0.1
  padj_cutoff_poisson: 0.01
  padj_cutoff_wilcox: 0.01

paths:
  lsgkm: "/gpfs/scratch/jtl334/thesis/lsgkm"
  gkmQC: "/gpfs/scratch/jtl334/thesis/gkmQC"